# http://docs.travis-ci.com/user/languages/go/
language: go

go:
  - 1.8

# http://docs.travis-ci.com/user/languages/go/#Dependency-Management
install:
   - go get github.com/stretchr/testify
   - go get github.com/hashicorp/go-cleanhttp
   - go get github.com/b3ntly/elasticsearch/mock
   - go get github.com/gorilla/mux
   - go get github.com/oklog/ulid
   - go get golang.org/x/tools/cmd/cover
   - go get github.com/axw/gocov/gocov
   - go get github.com/modocache/gover
   - go get github.com/mattn/goveralls

script:
  - go test
  #- go test -coverprofile=main.coverprofile
  #- $HOME/gopath/bin/gover
  #- $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci

before_install:
 - go get github.com/mattn/goveralls

#after_success:
#  - coveralls

before_script:
  - sleep 10

addons:
  apt:
    sources:
      - elasticsearch-2.x
    packages:
    - elasticsearch

services:
  - elasticsearch